# Generated by Django 3.2 on 2021-05-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='completedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
